pipeline {
  agent any
  stages {
    stage('Build Product Service') {
      steps {
        sh 'docker build -t secureshop/product-service apps/product-service'
      }
    }
    stage('Build Order Service') {
      steps {
        sh 'docker build -t secureshop/order-service apps/order-service'
      }
    }
    stage('SonarQube Analysis') {
      steps {
        withSonarQubeEnv('SonarQube') {
              sh 'sonar-scanner -Dsonar.projectKey=secureshop -Dsonar.sources=apps/product-service -Dsonar.host.url=http://host.docker.internal:9000 -Dsonar.login=squ_97493656137ebbf15b4795ff849f0ee696ef6dab'
        }
      }
    }
  }
}

